# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ROBOspeak1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from PyQt5.QtTextToSpeech import QTextToSpeech


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(255, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # lineEdit For write Text 

        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(180, 80, 451, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 80, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(650, 80, 93, 41))
        font = QtGui.QFont()
        font.setPointSize(14)

        # Button 

        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        # Pushbutton Connection

        self.pushButton.clicked.connect(self.say)



        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 10, 531, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 180, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        #combo Button For Voice Selection


        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(180, 170, 441, 41))
        self.comboBox.setObjectName("comboBox")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 350, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)

        # Create Lable 

        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        # horizontalSlider for Volume set


        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(180, 360, 421, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # text To Speech logic using ingine

        self.engine = None
        engineName = QTextToSpeech.availableEngines()

        if len(engineName) > 0:
            engineName = engineName[0]
            self.engine=QTextToSpeech(engineName)
            self.engine.stateChanged.connect(self.stateChanged)

            self.Voices=[]

            for voice in self.engine.availableVoices():
                self.Voices.append(voice)
                self.comboBox.addItem(voice.name())
            else:
                self.pushButton.setEnabled(True)

    def stateChanged(self,state):

        if(state == QTextToSpeech.stateChanged):
            self.pushButton.setEnabled(True)

    def say(self):
        self.pushButton.setEnabled(True)
        self.engine.setVoice(self.Voices[self.comboBox.currentIndex()])
        self.engine.setVolume(float(self.horizontalSlider.value() / 100))
        self.engine.say(self.lineEdit.text())


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Enter text"))
        self.pushButton.setText(_translate("MainWindow", "say"))
        self.label_2.setText(_translate("MainWindow", "Welcome To Ganes\'s RoboSpeaker 1.0. Created by Ganesh"))
        self.label_3.setText(_translate("MainWindow", "Voices:"))
        self.label_4.setText(_translate("MainWindow", "Volume"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
